# Generated by Django 4.0.6 on 2022-07-08 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category Title')),
                ('slug', models.SlugField(max_length=55, verbose_name='Category Slug')),
                ('description', models.TextField(blank=True, verbose_name='Category Description')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Category Image')),
                ('is_active', models.BooleanField(verbose_name='Is Active?')),
                ('is_featured', models.BooleanField(verbose_name='Is Featured?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(default='Object', max_length=255)),
                ('offer_title', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_image', models.FileField(null=True, upload_to='offer_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_image', models.FileField(null=True, upload_to='product_images/')),
                ('slug', models.SlugField(max_length=160, null=True, verbose_name='Product Slug')),
                ('is_featured', models.BooleanField(null=True, verbose_name='Is Featured?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='Product Categoy')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_red_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_sale_words', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_image', models.FileField(null=True, upload_to='sale_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=255)),
                ('slider_sale', models.CharField(blank=True, max_length=255, null=True)),
                ('slider_tittle', models.CharField(blank=True, max_length=255, null=True)),
                ('slider_image', models.FileField(blank=True, null=True, upload_to='slider_images/')),
                ('slider_slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='product_images/')),
                ('place', models.IntegerField(null=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.products')),
            ],
        ),
    ]
