# Generated by Django 4.0.6 on 2022-07-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Not available', 'Not available')], max_length=255, null=True),
        ),
    ]
