# Generated by Django 4.0.6 on 2022-07-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_productssize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
