# Generated by Django 4.0.6 on 2022-07-09 13:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Category Description'),
        ),
    ]
