# Generated by Django 4.0.6 on 2022-07-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_type_products_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='slug',
        ),
    ]
