# Generated by Django 4.0.6 on 2022-07-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_teadetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='kind_of_tea',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
