# Generated by Django 4.0.6 on 2022-07-16 21:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_products_kind_of_tea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_percent',
            field=models.IntegerField(null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_featured',
            field=models.BooleanField(null=True, verbose_name='Это один из лучших товаров?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='kind_of_tea',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип чая'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.FileField(null=True, upload_to='product_images/', verbose_name='Основное изображение товара(Обложка)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=160, null=True, verbose_name='Ссылка продукта'),
        ),
    ]
