# Generated by Django 4.0.6 on 2022-07-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_delete_productssize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='available',
            field=models.CharField(choices=[('В наличии', 'В наличии'), ('Нет в наличии', 'Нет в наличии')], max_length=255, null=True, verbose_name='Товар в наличии?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='kind_of_tea',
            field=models.CharField(choices=[('В пакете', 'В пакете'), ('Листья', 'Листья')], max_length=255, null=True, verbose_name='Тип чая'),
        ),
        migrations.AlterField(
            model_name='productsimage',
            name='images',
            field=models.FileField(upload_to='product_images/', verbose_name='Дополнительные снимки продукта'),
        ),
        migrations.AlterField(
            model_name='productsimage',
            name='place',
            field=models.IntegerField(null=True, verbose_name='Какая фотка по очереди?'),
        ),
    ]
