# Generated by Django 4.0.6 on 2022-07-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_products_available_alter_products_kind_of_tea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type_of_tea',
            field=models.CharField(choices=[('В пакете', 'В пакете'), ('Листья', 'Листья')], max_length=255, null=True, verbose_name='Тип чая'),
        ),
        migrations.AlterField(
            model_name='products',
            name='kind_of_tea',
            field=models.CharField(choices=[('Черный', 'Черный'), ('Зеленый', 'Зеленый'), ('Белый', 'Белый'), ('Желтый', 'Желтый'), ('Улун', 'Улун'), ('Пуэр', 'Пуэр')], max_length=255, null=True, verbose_name='Тип чая'),
        ),
    ]
