# Generated by Django 4.0.6 on 2022-07-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_products_type_of_tea_alter_products_kind_of_tea'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='number_of_suchets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sort_of_tea',
            field=models.CharField(max_length=255, null=True, verbose_name='Сорт чая'),
        ),
        migrations.AlterField(
            model_name='products',
            name='kind_of_tea',
            field=models.CharField(choices=[('Черный', 'Черный'), ('Зеленый', 'Зеленый'), ('Белый', 'Белый'), ('Желтый', 'Желтый'), ('Улун', 'Улун'), ('Пуэр', 'Пуэр')], max_length=255, null=True, verbose_name='Вид чая'),
        ),
    ]
