# Generated by Django 4.0.6 on 2022-07-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_products_number_of_suchets_products_sort_of_tea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tea_shapes',
            field=models.CharField(choices=[('Крупный', 'Крупный'), ('Средний', 'Средний'), ('Мелкий', 'Мелкий'), ('Прессованный', 'Прессованный')], max_length=255, null=True, verbose_name='Вид чая'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_of_tea',
            field=models.CharField(choices=[('Чай в пакетиках', 'Чай в пакетиках'), ('Чай листовый', 'Чай листовый')], max_length=255, null=True, verbose_name='Тип чая'),
        ),
    ]
