# Generated by Django 4.0.6 on 2022-07-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_products_tea_leaf_size_alter_products_tea_shapes'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='weight_of_product',
            field=models.IntegerField(null=True),
        ),
    ]
