# Generated by Django 4.0.6 on 2022-07-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_products_kind_of_tea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
