# Generated by Django 4.0.6 on 2022-07-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type_of_tea',
        ),
        migrations.AddField(
            model_name='products',
            name='type_of_product',
            field=models.CharField(blank=True, choices=[('Чай в пакетиках', 'Чай в пакетиках'), ('Чай листовый', 'Чай листовый'), ('Кофе растворимый', 'Кофе растворимый')], max_length=255, null=True, verbose_name='Тип чая'),
        ),
    ]
