# Generated by Django 4.0.6 on 2022-07-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_remove_products_type_of_tea_products_type_of_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='coffe_roasting',
            field=models.CharField(blank=True, choices=[('Слабообжаренный кофе', 'Слабообжаренный кофе'), ('Среднеобжаренный кофе', 'Среднеобжаренный кофе'), ('Сильнообжаренный кофе', 'Сильнообжаренный кофе'), ('Высшая степень обжарки кофе', 'Высшая степень обжарки кофе')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='composition_of_coffee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='taste_intensity',
            field=models.CharField(blank=True, choices=[('Крепкий', 'Крепкий'), ('Мягкий', 'Мягкий')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_of_product',
            field=models.CharField(blank=True, choices=[('Чай в пакетиках', 'Чай в пакетиках'), ('Чай листовый', 'Чай листовый'), ('Кофе растворимый', 'Кофе растворимый')], max_length=255, null=True, verbose_name='Тип товара'),
        ),
    ]
