# Generated by Django 4.0.6 on 2022-07-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_products_coffe_roasting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='arabica_content',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='coffe_roasting',
            field=models.CharField(blank=True, choices=[('Слабообжаренный кофе', 'Слабообжаренный кофе'), ('Среднеобжаренный кофе', 'Среднеобжаренный кофе'), ('Сильнообжаренный кофе', 'Сильнообжаренный кофе'), ('Высшая степень обжарки кофе', 'Высшая степень обжарки кофе')], max_length=255, null=True, verbose_name='Степень обжарки зерен'),
        ),
        migrations.AlterField(
            model_name='products',
            name='taste_intensity',
            field=models.CharField(blank=True, choices=[('Крепкий', 'Крепкий'), ('Мягкий', 'Мягкий')], max_length=255, null=True, verbose_name='Интенсивность вкуса'),
        ),
    ]
