# Generated by Django 4.0.6 on 2022-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_products_arabica_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='producting_technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_of_product',
            field=models.CharField(blank=True, choices=[('Чай в пакетиках', 'Чай в пакетиках'), ('Чай листовый', 'Чай листовый'), ('Кофе растворимый', 'Кофе растворимый'), ('Кофе в зернах', 'Кофе в зернах')], max_length=255, null=True, verbose_name='Тип товара'),
        ),
    ]
