# Generated by Django 4.0.6 on 2022-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_products_arabica_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=160, null=True, unique=True, verbose_name='Ссылка продукта'),
        ),
    ]
