# Generated by Django 4.0.6 on 2022-07-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='product_images/', verbose_name='Основное изображение товара(Обложка)'),
        ),
    ]
