# Generated by Django 4.0.6 on 2022-07-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_featured',
            field=models.BooleanField(default=False, null=True, verbose_name='Это один из лучших товаров?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='taste_intensity',
            field=models.CharField(blank=True, choices=[('Крепкий', 'Крепкий'), ('Средний', 'Средний'), ('Мягкий', 'Мягкий')], max_length=255, null=True, verbose_name='Интенсивность вкуса'),
        ),
    ]
