# Generated by Django 4.0.6 on 2022-07-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_alter_products_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Это один из лучших товаров?'),
        ),
    ]
