# Generated by Django 4.0.6 on 2022-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_alter_products_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_exclusive',
            field=models.BooleanField(default=False, verbose_name='Это один из эксклюзивных товаров?'),
        ),
    ]
