# Generated by Django 4.0.6 on 2022-07-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_brand_alter_category_slug_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=55, null=True, verbose_name='(Это поле создасться автоматически.Ее заполнять не нужно!)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=55, null=True, verbose_name='(Это поле создасться автоматически.Ее заполнять не нужно!)'),
        ),
    ]
