# Generated by Django 4.0.6 on 2022-07-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_alter_brand_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.brand', verbose_name='Брэнд товара'),
        ),
    ]
