# Generated by Django 4.0.6 on 2022-07-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
