# Generated by Django 4.0.6 on 2022-07-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_productcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
