# Generated by Django 4.0.6 on 2022-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_delete_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='pages.category', verbose_name='Категория товара'),
        ),
    ]
