# Generated by Django 4.0.6 on 2022-07-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_remove_products_category_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, to='pages.category', verbose_name='Категория товара'),
        ),
    ]
