# Generated by Django 4.0.6 on 2022-08-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_alter_products_tea_shapes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
