# Generated by Django 4.0.6 on 2022-08-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_delete_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True, verbose_name='(Это поле создасться автоматически.Ее заполнять не нужно!)'),
        ),
    ]
