# Generated by Django 4.0.6 on 2022-09-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
