# Generated by Django 4.0.6 on 2022-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_rename_email_order_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
